name: AWS Lambda infra CI/CD Feature
on:
  push:
    branches: [ feature/* ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'cdk/azure/**'
      - 'software/infrastructure/azure/**'
      - ".github/workflows/**-azure.yml"
  workflow_dispatch:

jobs:
  call-workflow-build-deploy:
    uses: ./.github/workflows/workflow-build-deploy-aws.yml
    with:
      role_name: ${{ secrets.OIDC_ROLE_NAME }}
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
