name: AWS Lambda infra CI/CD Main
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'cdk/azure/**'
      - 'software/infrastructure/azure/**'
      - ".github/workflows/**-azure.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  call-workflow-build-deploy:
    uses: ./.github/workflows/workflow-build-deploy-aws.yml
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      role_name: ${{ secrets.OIDC_ROLE_NAME }}